Description:
  Cloudformation use to create a stack according to cloud nanodegree project two requirement, Developed by Muhammad zarak.

Parameters:
    Environment:
        Description: Distinguish which enviroment this resource is
        Type: String
        Default: dev
        AllowedValues: 
        - prod
        - dev
        - staging

    InstanceID:
        Description: Instance id to create according to the load required
        Type: String
        Default: a1.large
        AllowedValues: 
        - a1.2xlarge
        - a1.4xlarge
        - a1.medium
        - a1.xlarge

    ScaleInCapacity:
        Description: Lowest number of instance required when no or minimum load applicable
        Type: String
        Default: '1'

    ScaleOutCapacity:
        Description: Lowest number of instance required when no or minimum load applicable
        Type: String
        Default: '3'

Resources:
    WebAppInstances:
        Type: AWS::AutoScaling::AutoScalingGroup
        Properties:
            VPCZoneIdentifier:
            - Fn::ImportValue: !Sub "${Environment}-PRIV-NETS"
            LaunchConfigurationName:
                Ref: InstanceLaunchConfig
            MinSize: !Ref ScaleInCapacity
            MaxSize: !Ref ScaleOutCapacity
            TargetGroupARNs:
            - Ref: ApplicationTargetGroup

    InstanceLaunchConfig:
        Type: AWS::AutoScaling::LaunchConfiguration
        Properties:
            UserData:
                Fn::Base64: !Sub |
                    #!/bin/bash 
                    sudo apt-get update -y
                    sudo apt-get install apache2 -y
                    sudo systemctl start apache2.service
                    sudo rm /var/www/html/index.html
                    sudo wget -P /var/www/html/ https://nanodegree-zarak-s3-project.s3.amazonaws.com/index.html
            ImageId: "ami-0f494dc39ae364f3d"
            SecurityGroups:
                - Ref: ApplicationSecurityGroup
            InstanceType: !Ref InstanceID
            BlockDeviceMappings:
                - DeviceName: "/dev/sdk"
                  Ebs:
                    VolumeSize: '20'

    ApplicationLoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Subnets:
            - Fn::ImportValue: !Sub "${Environment}-PUB1-SN"
            - Fn::ImportValue: !Sub "${Environment}-PUB2-SN"
            SecurityGroups:
            - Ref: LoadBalancerSecurityGroup
    
    ALBListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            DefaultActions:
            - Type: forward
              TargetGroupArn:
                Ref: ApplicationTargetGroup
            LoadBalancerArn: !Ref ApplicationLoadBalancer
            Port: '80'
            Protocol: HTTP

    ALBListenerRule:
        Type: AWS::ElasticLoadBalancingV2::ListenerRule
        Properties:
            Actions:
            - Type: forward
              TargetGroupArn: !Ref 'ApplicationTargetGroup'
            Conditions:
            - Field: path-pattern
              Values: [/]
            ListenerArn: !Ref 'ALBListener'
            Priority: 1

    ApplicationTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            HealthCheckIntervalSeconds: 20
            HealthCheckPath: /
            HealthCheckProtocol: HTTP
            Port: 80
            HealthCheckTimeoutSeconds: 5
            HealthyThresholdCount: 3
            Protocol: HTTP
            UnhealthyThresholdCount: 3
            VpcId:
              Fn::ImportValue:
                Fn::Sub: "${Environment}-VPCID"

    LoadBalancerSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allow HTTP Traffic to Load Balancer to port 80
            VpcId:
                Fn::ImportValue: !Sub "${Environment}-VPCID"
            SecurityGroupIngress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0
            SecurityGroupEgress:
            - IpProtocol: tcp
              FromPort: 80
              ToPort: 80
              CidrIp: 0.0.0.0/0

    ApplicationSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
          GroupDescription: hosts and SSH allowed to local
          VpcId:
            Fn::ImportValue:
              !Sub "${Environment}-VPCID"
          SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 80
            ToPort: 80
            CidrIp: 0.0.0.0/0
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 0.0.0.0/0
          SecurityGroupEgress:
          - IpProtocol: tcp
            FromPort: 0
            ToPort: 65535
            CidrIp: 0.0.0.0/0

Outputs:
    LoadBalancerDNS:
        Value: !Join [ "", [ 'http://', !GetAtt WebAppLB.DNSName ]]
        Export:
            Name: "http-url" 